
{% set rdir = "../.." %}
{% set data = load_setup_py_data(setup_file=''+rdir+'/setup.py', from_recipe_dir=True) %}

package:
  name: bicleaner-ai
  version: {{ data.get('version') }}

source:
  path: {{ rdir }}

build:
  string: "py{{ environ.get('CONDA_PY') }}_{{ environ.get('GIT_DESCRIBE_HASH') }}"
  preserve_egg_dir: True

requirements:
  host:
    - pip
    - setuptools
    - python {{ python }}
  run:
    - python {{ python }}
    - kenlm
    - fastspell

about:
  home: https://github.com/bitextor/bicleaner-ai
  license: GPL3
  summary: Bicleaner fork that uses neural networks
