#!/usr/bin/env python
import os
# Suppress Tenssorflow logging messages unless log level is explictly set
if 'TF_CPP_MIN_LOG_LEVEL' not in os.environ:
    os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
import sys
import bicleaner_ai.bicleaner_ai_train as train

def main(argv):
    args = train.initialization()
    train.main(args)

if __name__ == '__main__':
    main(sys.argv[1:])
