#!/usr/bin/env python

import sys
import bicleaner_ai.bicleaner_ai_train as train

def main(argv):
    args = train.initialization()
    train.main(args)

if __name__ == '__main__':
    main(sys.argv[1:])
